swagger: '2.0'
info:
  title: 'test-app-sitebricks'
  description: 'simple test app with sitebricks'
  version: '1.0-SNAPSHOT'
host: "test-app-sitebricks.appspot.com"
schemes:
  - https
produces:
  - "application/json"
consumes:
  - "application/json"
basePath: "/v1"
paths:
  /v1/users:
    get:
      summary: "returns all users registered in the system"
      operationId: getUsers
      responses:
        200:
          description: "successfully return all users"
    post:
      summary: "register user in the system"
      operationId: registerUser
      parameters:
      - in: body
        name: user
        description: "user that should be added to the system"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: "user registered successful"
        400:
          description: "invalid consumed data"
  /v1/users/{ucn}:
    get:
      summary: "find user by given ucn"
      operationId: findUserById
      parameters:
      - name: ucn
        in: path
        description: "ucn of user to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "returns required user successful"
        400:
          description: "invalid ucn of user"
    delete:
      summary: "delete a user"
      operationId: deleteUserById
      parameters:
      - name: ucn
        in: path
        description: "ucn of user that wants to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "user was deleted successfully"
        400:
          description: "invalid user ucn"
  /accounts/{ucn}/tokenBalance:
    get:
      summary: "returns user account tokenBalance"
      operationId: getUserBalance
      parameters:
      - name: ucn
        in: path
        description: "ucn of user that want to get tokenBalance"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "return tokenBalance of user successfully"
        400:
          description: "invalid user ucn"
  /accounts/{ucn}/deposit:
    post:
      summary: "deposit amount to user account"
      operationId: deposit
      parameters:
        - in: body
          name: amount
          description: "amount to deposit"
          required: true
          schema:
            type: "integer"
        - name: ucn
          in: path
          description: "ucn of user in that account we want to deposit"
          required: true
          type: "integer"
          format: "int64"
      responses:
          200:
            description: "deposit was successfully"
          400:
            description: "user does not exist"
  /accounts/{ucn}/withdraw:
    post:
      summary: "withdraw from user account"
      operationId: withdraw
      parameters:
        - in: body
          name: amount
          description: "amount to withdraw"
          required: true
          schema:
            type: "integer"
        - name: ucn
          in: path
          description: "ucn of user in that account we want to  withdraw"
          required: true
          type: "integer"
          format: "int64"
      responses:
          200:
            description: "withdraw was successfully"
          400:
            description: "no such amount or invalid user ucn"
definitions:
  User:
    type: "object"
    properties:
      ucn:
        type: "integer"
        format: "int64"
      name:
        type: "string"